### ISSUE TITLE
数据少有问题

### ISSUE THREAD

**Issue by db5433** [hwh97/chat_demo#1]

**Comment by hwh97** [comment]
数据未满一屏，滑动关闭了，可以指定ChatScrollPhysics的parent为AlwaysScrollableScrollPhysics
```physics: ChatScrollPhysics(parent: AlwaysScrollableScrollPhysics())```

同时可以用maxScrollExtent==0判断首次加载列表是否满一屏,未满直接调用加载更多。

已更新Demo 感谢反馈
